spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:market}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
